/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps/$appId'
import { Route as AppErrorsErrorRouteImport } from './routes/_app/errors/$error'
import { Route as AppFabsIndexRouteImport } from './routes/_app/fabs/index'
import { Route as AppForecastIndexRouteImport } from './routes/_app/forecast/index'
import { Route as AppMarketIndexRouteImport } from './routes/_app/market/index'
import { Route as AppOemIndexRouteImport } from './routes/_app/oem/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppRevenueIndexRouteImport } from './routes/_app/revenue/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppErrorsErrorRoute = AppErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFabsIndexRoute = AppFabsIndexRouteImport.update({
  id: '/fabs/',
  path: '/fabs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForecastIndexRoute = AppForecastIndexRouteImport.update({
  id: '/forecast/',
  path: '/forecast/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOemIndexRoute = AppOemIndexRouteImport.update({
  id: '/oem/',
  path: '/oem/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRevenueIndexRoute = AppRevenueIndexRouteImport.update({
  id: '/revenue/',
  path: '/revenue/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apps/$appId': typeof AppAppsAppIdRoute
  '/errors/$error': typeof AppErrorsErrorRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/apps/': typeof AppAppsIndexRoute
  '/fabs/': typeof AppFabsIndexRoute
  '/forecast/': typeof AppForecastIndexRoute
  '/market/': typeof AppMarketIndexRoute
  '/oem/': typeof AppOemIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/revenue/': typeof AppRevenueIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AppIndexRoute
  '/apps/$appId': typeof AppAppsAppIdRoute
  '/errors/$error': typeof AppErrorsErrorRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/apps': typeof AppAppsIndexRoute
  '/fabs': typeof AppFabsIndexRoute
  '/forecast': typeof AppForecastIndexRoute
  '/market': typeof AppMarketIndexRoute
  '/oem': typeof AppOemIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/revenue': typeof AppRevenueIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$appId': typeof AppAppsAppIdRoute
  '/_app/errors/$error': typeof AppErrorsErrorRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/fabs/': typeof AppFabsIndexRoute
  '/_app/forecast/': typeof AppForecastIndexRoute
  '/_app/market/': typeof AppMarketIndexRoute
  '/_app/oem/': typeof AppOemIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/revenue/': typeof AppRevenueIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apps/$appId'
    | '/errors/$error'
    | '/settings/appearance'
    | '/apps/'
    | '/fabs/'
    | '/forecast/'
    | '/market/'
    | '/oem/'
    | '/orders/'
    | '/revenue/'
    | '/sales/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/apps/$appId'
    | '/errors/$error'
    | '/settings/appearance'
    | '/apps'
    | '/fabs'
    | '/forecast'
    | '/market'
    | '/oem'
    | '/orders'
    | '/revenue'
    | '/sales'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_app/'
    | '/_app/apps/$appId'
    | '/_app/errors/$error'
    | '/_app/settings/appearance'
    | '/_app/apps/'
    | '/_app/fabs/'
    | '/_app/forecast/'
    | '/_app/market/'
    | '/_app/oem/'
    | '/_app/orders/'
    | '/_app/revenue/'
    | '/_app/sales/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/apps/$appId': {
      id: '/_app/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/errors/$error': {
      id: '/_app/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AppErrorsErrorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fabs/': {
      id: '/_app/fabs/'
      path: '/fabs'
      fullPath: '/fabs/'
      preLoaderRoute: typeof AppFabsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/forecast/': {
      id: '/_app/forecast/'
      path: '/forecast'
      fullPath: '/forecast/'
      preLoaderRoute: typeof AppForecastIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/market/': {
      id: '/_app/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/oem/': {
      id: '/_app/oem/'
      path: '/oem'
      fullPath: '/oem/'
      preLoaderRoute: typeof AppOemIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/revenue/': {
      id: '/_app/revenue/'
      path: '/revenue'
      fullPath: '/revenue/'
      preLoaderRoute: typeof AppRevenueIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAppsAppIdRoute: typeof AppAppsAppIdRoute
  AppErrorsErrorRoute: typeof AppErrorsErrorRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppFabsIndexRoute: typeof AppFabsIndexRoute
  AppForecastIndexRoute: typeof AppForecastIndexRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppOemIndexRoute: typeof AppOemIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppRevenueIndexRoute: typeof AppRevenueIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAppsAppIdRoute: AppAppsAppIdRoute,
  AppErrorsErrorRoute: AppErrorsErrorRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppFabsIndexRoute: AppFabsIndexRoute,
  AppForecastIndexRoute: AppForecastIndexRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppOemIndexRoute: AppOemIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppRevenueIndexRoute: AppRevenueIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
